services:
  db:
    container_name: db 
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "auth_demo"
    ports:
      - "5432:5432"
